// all-learn-data/17.每日作业/2021.1.28作业/angularhuayu/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http'
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angularhuayu';
  musiclist = [];
  constructor(public http: HttpClient) { }
  ngOnInit() {
    let url = "http://localhost:4000/top/playlist?cat=华语"
    this.http.get(url).subscribe((res: any) => {
      console.log(res)
      this.musiclist = res.playlists
    })
  }
}

<app-musicitem [musiclist]="musiclist"></app-musicitem>

// all-learn-data/17.每日作业/寒假作业/2021-2-1作业/vuecomponent/src/App.vue
<template>
  <div id="app">
    <huayu :playlist="item" v-for="item of playlists" :key="item.id"></huayu>
  </div>
</template>

<script>
import axios from "axios";
import huayu from "./components/huayu";
export default {
  name: "App",
  components: {
    huayu,
  },
  data() {
    return {
      playlists: [],
    };
  },
  mounted() {
    axios.get("http://localhost:4000/top/playlist?cat=华语").then((res) => {
      this.playlists = res.data.playlists;
      // console.log(res);
    });
  },
};
</script>

<style>
#app {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
}
</style>
