// all-learn-data/2.Vue/httpgetmovie/src/App.vue
<template>
  <div id="app">
    <div>app</div>
    <movie-item
      v-for="item of movies"
      :key="item.title"
      :item="item"
    ></movie-item>
  </div>
</template>

<script>
import axios from "axios";
import MovieItem from "./components/MovieItem";
export default {
  name: "App",
  components: {
    MovieItem,
  },
  data() {
    return {
      movies: [],
    };
  },
  mounted() {
    //mounted生命周期函数中可以获取DOM因此在mounted中进行HTTP请求
    axios.get("http://localhost:8000/top250").then((res) => {
      // console.log(res.data.result);
      this.movies = res.data.result;
    });
  },
};
</script>

<style>
</style>

// react-cli-simple-page/src/App.js
// function App() {
//   return (
//     <p>hello world</p>
//   );
// }

// export default App;
// 继承的方式实现
import React, { Component } from 'react'
import './App.css'
import axios from 'axios'
import Musicitem from './components/Musicitem'
export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      movies: [],
      child: "music"
    }
  }
  render() {
    return (
      <div className="test">
        hello world
        <Musicitem data={this.state.child}></Musicitem>
      </div>
    )
  }
  componentDidMount() {
    let url = "http://localhost:8000/top250"
    axios.get(url).then(res => {
      this.setState({
        movies: res.data.result
      })
      console.log(this.state.movies)
    })
  }
}
