// react-cli-simple-page/src/App.js
// function App() {
//   return (
//     <p>hello world</p>
//   );
// }

// export default App;
// 继承的方式实现
import React, { Component } from 'react'
import './App.css'
import axios from 'axios'
import Musicitem from './components/Musicitem'
export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      movies: [],
      child: "music"
    }
  }
  render() {
    return (
      <div className="test">
        hello world
        <Musicitem data={this.state.child}></Musicitem>
      </div>
    )
  }
  componentDidMount() {
    let url = "http://localhost:8000/top250"
    axios.get(url).then(res => {
      this.setState({
        movies: res.data.result
      })
      console.log(this.state.movies)
    })
  }
}

// all-learn-data/2.Vue/总结/frontend-notebook/Vue/demo/src/App.vue
<template>
  <div id="app">
      {{msg | handleStr}}
  </div>
</template>
<script>
import Vue from 'vue'
export default {
  name:"App",
  data(){
    return {
      msg:"你姐姐傅雷家书地方"
    }
  },
  mounted(){
    console.log(this instanceof Vue)
    this.$http.get("http://192.168.4.20:8000/top250").then(res=>{
      console.log(res)
    })
  }
}
</script>
